-- Run as database administrator. Uses two existing profiles without farms;
-- timestamps are moved ONLY inside this rolled-back verification transaction.
begin;
do $$
declare a uuid; b uuid; c uuid; r jsonb; denied boolean; before_points jsonb; after_points jsonb;
begin
  select id into a from public.profiles where not exists(select 1 from public.pixel_farm_plots where user_id=profiles.id) limit 1;
  select id into b from public.profiles where id<>a and not exists(select 1 from public.pixel_farm_plots where user_id=profiles.id) limit 1;
  if a is null or b is null then raise exception 'Two profiles without farms required'; end if;
  select jsonb_build_array(bonus_points,point_adjustment) into before_points from public.profiles where id=a;
  perform set_config('request.jwt.claim.sub',a::text,true);
  execute 'set local role authenticated';
  r := public.get_pixel_farm();
  if jsonb_array_length(r->'plots')<>2 or (r->>'harvestCount')::int<>0 then raise exception 'empty farm failed'; end if;
  r := public.act_pixel_farm(0,'plant',0);
  c := (r#>>'{plots,0,crop,id}')::uuid;
  if c is null or r->>'result'<>'ok' then raise exception 'plant failed %',r; end if;
  if (r#>>'{plots,0,crop,readyAt}')::timestamptz - (r#>>'{plots,0,crop,plantedAt}')::timestamptz <> interval '24 hours' then raise exception 'growth duration'; end if;
  r := public.act_pixel_farm(0,'plant',0);
  if r->>'result'<>'changed' or (r#>>'{plots,0,crop,id}')::uuid<>c then raise exception 'duplicate plant'; end if;
  r := public.act_pixel_farm(0,'water',1);
  if (r#>>'{plots,0,crop,careCount}')::int<>1 then raise exception 'water failed'; end if;
  r := public.act_pixel_farm(0,'water',1);
  if r->>'result'<>'changed' then raise exception 'stale revision accepted'; end if;
  r := public.act_pixel_farm(0,'water',2);
  if r->>'result'<>'already_watered' or (select count(*) from public.pixel_farm_care)<>1 then raise exception 'duplicate care'; end if;
  r := public.act_pixel_farm(0,'harvest',2);
  if r->>'result'<>'growing' then raise exception 'early harvest'; end if;
  denied:=false;
  begin update public.pixel_farm_crops set ready_at=now() where id=c; exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'direct timestamp forgery allowed'; end if;
  denied:=false;
  begin perform public.act_pixel_farm(2,'plant',0); exception when invalid_parameter_value then denied:=true; end;
  if not denied then raise exception 'extra plot allowed'; end if;
  -- Simulate yesterday's care, then verify a new KST day can be recorded once.
  execute 'reset role';
  update public.pixel_farm_care set care_day=care_day-1,watered_at=watered_at-interval '1 day' where crop_id=c;
  update public.pixel_farm_crops set last_watered_on=last_watered_on-1 where id=c;
  execute 'set local role authenticated';
  r := public.act_pixel_farm(0,'water',2);
  if (r#>>'{plots,0,crop,careCount}')::int<>2 then raise exception 'next day care'; end if;
  r := public.act_pixel_farm(1,'plant',0);
  -- No water for a week must still produce a harvestable crop.
  execute 'reset role';
  update public.pixel_farm_crops set planted_at=clock_timestamp()-interval '7 days',ready_at=clock_timestamp()-interval '6 days' where user_id=a;
  perform set_config('request.jwt.claim.sub',b::text,true);
  execute 'set local role authenticated';
  if exists(select 1 from public.pixel_farm_crops where user_id=a) or exists(select 1 from public.pixel_farm_care where user_id=a) or exists(select 1 from public.pixel_farm_plots where user_id=a) then raise exception 'cross-user read'; end if;
  if public.get_pixel_farm()#>>'{plots,0,crop}' is not null then raise exception 'snapshot leaked crop'; end if;
  r := public.act_pixel_farm(0,'harvest',3);
  if r->>'result'<>'changed' then raise exception 'cross-user action'; end if;
  execute 'reset role';
  perform set_config('request.jwt.claim.sub',a::text,true);
  execute 'set local role authenticated';
  r := public.act_pixel_farm(0,'harvest',3);
  if r->>'result'<>'ok' or (r->>'harvestCount')::int<>1 or r#>>'{plots,0,crop}' is not null then raise exception 'harvest failed %',r; end if;
  r := public.act_pixel_farm(0,'harvest',3);
  if r->>'result'<>'changed' or (r->>'harvestCount')::int<>1 then raise exception 'duplicate harvest'; end if;
  r := public.act_pixel_farm(1,'harvest',1);
  if r->>'result'<>'ok' or (r->>'harvestCount')::int<>2 then raise exception 'unwatered crop lost'; end if;
  if not exists(select 1 from public.pixel_farm_crops where id=c and harvested_at is not null and care_count=2) then raise exception 'history lost'; end if;
  r := public.act_pixel_farm(0,'plant',4);
  if (r#>>'{plots,0,crop,id}')::uuid=c then raise exception 'replant reused old crop'; end if;
  r := public.act_pixel_farm(0,'harvest',3);
  if r->>'result'<>'changed' or r#>>'{plots,0,crop,id}' is null then raise exception 'old request mutated new crop'; end if;
  if public.get_pixel_farm()#>>'{plots,0,crop,id}' <> r#>>'{plots,0,crop,id}' then raise exception 'snapshot persistence'; end if;
  execute 'reset role';
  select jsonb_build_array(bonus_points,point_adjustment) into after_points from public.profiles where id=a;
  if before_points<>after_points then raise exception 'points changed'; end if;
  perform set_config('request.jwt.claim.sub','',true);
  execute 'set local role authenticated';
  denied:=false;
  begin perform public.act_pixel_farm(0,'plant',0); exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'missing uid allowed'; end if;
  execute 'reset role';
  execute 'set local role anon';
  denied:=false;
  begin perform public.get_pixel_farm(); exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'anonymous read allowed'; end if;
  denied:=false;
  begin perform public.act_pixel_farm(0,'plant',0); exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'anonymous action allowed'; end if;
  execute 'reset role';
end $$;
select 'PASS: lifecycle, KST daily care, revisions/retries, stale replant, missed watering, history, server time, unchanged points, RLS/anonymous denial; all rolled back' as result;
rollback;
