"""Build code-native pixel paths aligned to the original CC0 body/pants poses.
Reads atlases only; never edits existing art. Requires Pillow.
"""
from pathlib import Path
from PIL import Image
import json

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'src/features/pixel-room/assets/character'
result = {}
for animation in ('Idle', 'Walk'):
    for direction in ('Front', 'Back', 'Left', 'Right'):
        body = Image.open(ART / f'Character_{animation}_{direction}-Sheet.png').convert('RGBA')
        pants = Image.open(ART / f'Clothing_Bottoms_{animation}_{direction}-Sheet.png').convert('RGBA')
        poses = {'blouse': [], 'bootcut': []}
        for frame in range(4):
            skin = {(x,y) for y in range(18,26) for x in range(32) if body.getpixel((frame*32+x,y))[3]}
            center = round(sum(x for x,y in skin if y==19) / sum(y==19 for x,y in skin))
            blouse = {(x,y):1 for x,y in skin if y<=24}
            # Wide neckline, full sleeves and a gathered lower edge, not a recolored T-shirt.
            for x,y in list(blouse):
                if direction=='Front' and y<=19 and abs(x-center)<=3: del blouse[x,y]
                elif direction=='Back' and y==18 and abs(x-center)<=2: del blouse[x,y]
                elif direction in ('Left','Right') and y<=19 and ((direction=='Left' and x<center-1) or (direction=='Right' and x>center+1)): del blouse[x,y]
            for y in (20,21,22):
                row=[x for x,yy in skin if yy==y]
                if row:
                    blouse[min(row)-1,y]=1
                    blouse[max(row)+1,y]=1
            for x in range(center-4,center+5): blouse[x,25]=1
            for x,y in list(blouse):
                if any((x+dx,y+dy) not in blouse for dx,dy in ((1,0),(-1,0),(0,1),(0,-1))): blouse[x,y]=0
                elif x in (center-2,center+2) and y>=21: blouse[x,y]=2
            if direction=='Front':
                for x,y in ((center-1,20),(center+1,20),(center,21)): blouse[x,y]=3
            jeans={}
            for y in range(32):
                for x in range(32):
                    color=pants.getpixel((frame*32+x,8*32+y))
                    if color[3]: jeans[x,y]=0 if color[0]<140 else 2 if color[0]<165 else 1
            bottom=max(y for x,y in jeans)
            # Continue each moving leg to a broader hem. Keep the crotch gap open.
            for y in (bottom-1,bottom):
                row=sorted(x for x,yy in jeans if yy==y)
                if row:
                    jeans[row[0]-1,y]=0; jeans[row[-1]+1,y]=0
            if bottom<30:
                row=sorted(x for x,y in jeans if y==bottom)
                for x in row: jeans[x,bottom+1]=0 if x in (row[0],row[-1]) else 1
            top=min(y for x,y in jeans)
            for x,y in list(jeans):
                if y==top: jeans[x,y]=0
                elif x in (center-3,center+3) and y<bottom: jeans[x,y]=2
            if (center,top) in jeans: jeans[center,top]=3
            for kind,pixels in (('blouse',blouse),('bootcut',jeans)):
                # Four batched paths per garment instead of hundreds of SVG rects per avatar.
                paths=[]
                for shade in range(4):
                    path=''
                    for y in range(32):
                        xs=sorted(x for (x,yy),s in pixels.items() if yy==y and s==shade)
                        while xs:
                            start=xs.pop(0);end=start+1
                            while xs and xs[0]==end: xs.pop(0);end+=1
                            path+=f'M{start} {y}h{end-start}v1h-{end-start}z'
                    paths.append(path)
                poses[kind].append(paths)
        result[f'{animation}_{direction}']=poses
target=ROOT/'src/features/pixel-room/shop/fashionPaths.ts'
target.write_text('// Generated by scripts/build-fashion-paths.py. Existing atlases are unchanged.\nexport const FASHION_PATHS = '+json.dumps(result,separators=(',',':'))+' as const;\n',encoding='utf-8')
