import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
await mkdir('node_modules/.cache/plaza-interactions', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const errors = [];
  page.on('pageerror', error => { errors.push(error.message); console.log('BROWSER ERROR', error.stack); });
  await page.route('**/src/services/supabase.ts', route => route.fulfill({ contentType: 'application/javascript', body: "export { supabase } from '/tests/plaza/fakeRealtime.mjs';" }));
  await page.route('**/src/utils/pixelShop.ts', route => route.fulfill({ contentType: 'application/javascript', body: 'export async function fetchEquippedAppearance(){return {top:null,bottom:null,shoes:null,hair:null,eyes:null}}' }));
  await page.goto('http://127.0.0.1:5174/tests/plaza/landscape.html?peer');
  await page.getByRole('button', { name: '안녕!' }).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#peer-reactions').textContent).some(r => r.sessionId === 'viewer' && r.kind === 'wave'));
  assert.ok(await page.getByRole('button', { name: '안녕!' }).isDisabled());
  assert.equal(await page.evaluate(() => window.peerReact('cheer')), true);
  await page.waitForFunction(() => [...document.querySelectorAll('.pr-reaction-bubble')].some(el => el.textContent.includes('응원해')));
  assert.equal(await page.evaluate(() => window.peerReact('rest')), false, 'sender throttles immediately');
  await page.evaluate(() => {
    const now = Date.now();
    window.plazaTransport.reaction({ sessionId: 'peer', kind: 'rest', sentAt: now + 1 });
    window.plazaTransport.reaction({ sessionId: 'unknown', kind: 'wave', sentAt: now });
    window.plazaTransport.reaction({ sessionId: 'peer', kind: 'arbitrary private text', sentAt: now });
  });
  assert.equal(await page.locator('.pr-reaction-bubble').filter({ hasText: '잠깐 쉬자' }).count(), 0, 'receiver also throttles');
  await page.waitForTimeout(220);
  await page.screenshot({ path: 'node_modules/.cache/plaza-interactions/reactions-mobile.png' });
  await page.waitForFunction(() => document.querySelectorAll('.pr-reaction-bubble').length === 0);
  await page.getByRole('button', { name: '우물로 가기', exact: true }).click();
  await page.waitForFunction(() => { const p = window.plazaTransport.last('viewer'); return p.x === 7 && p.y === 6 && !p.moving; });
  await page.getByRole('button', { name: '꺼내 보기' }).click();
  await page.locator('.pr-well-message').waitFor();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#peer-reactions').textContent).some(r => r.kind === 'wish'));
  const firstMessage = await page.locator('.pr-well-message').innerText();
  assert.ok(await page.locator('.pr-well-ripple').count());
  await page.waitForTimeout(220);
  await page.screenshot({ path: 'node_modules/.cache/plaza-interactions/well-mobile.png' });
  await page.reload();
  await page.getByText('오늘의 한마디를 만났어요').waitFor();
  await page.getByRole('button', { name: '우물로 가기', exact: true }).click();
  await page.waitForFunction(() => { const p = window.plazaTransport.last('viewer'); return p.x === 7 && p.y === 6 && !p.moving; });
  await page.getByRole('button', { name: '다시 읽기' }).click();
  assert.equal(await page.locator('.pr-well-message').innerText(), firstMessage);
  assert.equal(await page.locator('.pr-well-ripple').count(), 0, 'rereading does not rebroadcast');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: 'node_modules/.cache/plaza-interactions/well-desktop.png' });
  await page.evaluate(() => window.plazaTransport.fail('viewer'));
  await page.waitForFunction(() => document.querySelector('.pr-reaction-status').textContent.includes('연결'));
  assert.ok(await page.getByRole('button', { name: '안녕!' }).isDisabled());
  await page.waitForFunction(() => !document.querySelector('.pr-reaction-bar button').disabled);
  await page.getByRole('button', { name: '안녕!' }).click();
  await page.waitForFunction(() => JSON.parse(document.querySelector('#peer-reactions').textContent).some(r => r.kind === 'wave'));
  await page.addInitScript(() => {
    Storage.prototype.getItem = () => { throw new Error('storage blocked'); };
    Storage.prototype.setItem = () => { throw new Error('storage blocked'); };
  });
  await page.goto('http://127.0.0.1:5174/tests/plaza/landscape.html');
  await page.getByRole('button', { name: '우물로 가기', exact: true }).click();
  await page.waitForFunction(() => { const p = window.plazaTransport.last('viewer'); return p.x === 7 && p.y === 6 && !p.moving; });
  await page.getByRole('button', { name: '꺼내 보기' }).click();
  await page.getByText('기록을 저장하지 못했어요. 이번 방문 동안만 기억해요.').waitFor();
  assert.ok(await page.locator('.pr-well-message').count(), 'solo activity still works with storage blocked');
  assert.deepEqual(errors, []);
  console.log('PASS bidirectional reactions, throttle/expiry, daily well + reload, reconnect');
} finally { await browser.close(); }
