import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const base = `${process.env.EXAM_TEST_BASE_URL || 'http://127.0.0.1:5174'}/tests/exam/practice.html`;
const out = `${process.env.EXAM_TEST_ARTIFACT_DIR || '.test-artifacts'}/peer-picker`;
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
async function checkCanvasPlayback(page, peer) {
  const canvas = peer.getByTestId('exam-peer-canvas');
  await peer.getByRole('slider').press('End');
  await peer.getByRole('slider').press('Home');
  await canvas.scrollIntoViewIfNeeded();
  const box = await canvas.boundingBox();
  const x = Math.round(box.x + box.width / 2), y = Math.round(box.y + 45);
  const paused = () => peer.getByRole('button', { name: '재생', exact: true });
  const playing = () => peer.getByRole('button', { name: '일시정지', exact: true });
  assert.equal(await paused().count(), 1);
  await page.touchscreen.tap(x, y);
  assert.equal(await playing().count(), 1, 'one-finger tap starts playback');
  await page.touchscreen.tap(x, y);
  assert.equal(await paused().count(), 1, 'one-finger tap pauses playback');
  assert.equal(await peer.getByTestId('exam-replay-feedback').isVisible(), true);
  await page.waitForTimeout(750);
  assert.equal(await peer.getByTestId('exam-replay-feedback').count(), 0);
  await page.mouse.move(x, y); await page.mouse.down();
  await page.mouse.move(x + 40, y + 30, { steps: 5 }); await page.mouse.up();
  assert.equal(await paused().count(), 1, 'drag does not toggle');
  await page.mouse.move(x, y); await page.mouse.down();
  await page.waitForTimeout(350); await page.mouse.up();
  assert.equal(await paused().count(), 1, 'long press does not toggle');
  await page.mouse.click(x, y);
  assert.equal(await playing().count(), 1, 'mouse click starts playback');
  await page.mouse.click(x, y);
  assert.equal(await paused().count(), 1);
  const cdp = await page.context().newCDPSession(page);
  const touch = (type, touchPoints) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints });
  await touch('touchStart', [{ x, y, id: 1 }]);
  await touch('touchMove', [{ x, y: y + 50, id: 1 }]);
  await touch('touchEnd', []);
  assert.equal(await paused().count(), 1, 'native touch scroll does not toggle');
  await canvas.scrollIntoViewIfNeeded();
  const next = await canvas.boundingBox();
  const px = Math.round(next.x + next.width / 2), py = Math.round(next.y + 45);
  await touch('touchStart', [{ x: px - 20, y: py, id: 1 }, { x: px + 20, y: py, id: 2 }]);
  await touch('touchMove', [{ x: px - 35, y: py + 10, id: 1 }, { x: px + 35, y: py + 10, id: 2 }]);
  await touch('touchEnd', []);
  assert.equal(await paused().count(), 1, 'pinch does not toggle');
  await touch('touchStart', [{ x: px - 20, y: py, id: 1 }, { x: px + 20, y: py, id: 2 }]);
  await touch('touchEnd', []);
  assert.equal(await paused().count(), 1, 'two-finger tap does not toggle');
  await cdp.detach();
}
try {
  for (const viewport of [{ width:390,height:844 }, { width:820,height:1180 }, { width:1024,height:768 }]) {
    const page = await browser.newPage({ viewport, hasTouch: true });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base);
    await page.getByTestId('exam-start').waitFor();
    await page.locator('.exam-paper-card[data-paper-id="2025-06-math"]').click();
    await page.getByRole('radio', { name:/자유 모드/ }).click();
    await page.getByRole('radio', { name:/확통/ }).click();
    await page.getByTestId('exam-start-button').click();
    await page.getByTestId('exam-solve').waitFor();
    await page.evaluate(() => {
      const original = window.__examClient.listPeerSolutions;
      window.__examClient.listPeerSolutions = async (...args) => {
        const rows = await original(...args);
        return [...rows.slice(0, 2), ...[3, 4].map(i => ({ ...rows[1], solutionKey: `extra-${i}` })), ...rows.slice(2)];
      };
    });
    const ownInk = page.locator('[data-testid="exam-body"] .exam-ink');
    await ownInk.waitFor();
    const inkBox = await ownInk.boundingBox();
    await page.mouse.move(inkBox.x + 30, inkBox.y + 40);
    await page.mouse.down();
    await page.mouse.move(inkBox.x + 100, inkBox.y + 80, { steps: 8 });
    await page.mouse.up();
    await page.waitForFunction(() => document.querySelector('[data-testid="exam-body"] .exam-ink')?.dataset.strokeCount === '1');
    const ownCanvas = await ownInk.elementHandle();
    assert.equal(await page.getByTestId('exam-free-peer').count(),0);
    await page.locator('.exam-choice[data-choice="3"]').click();
    await page.getByRole('button',{name:'채점해 보기',exact:true}).click();
    await page.getByTestId('exam-free-peer').click();
    const list = page.getByTestId('exam-peer-list');
    await list.waitFor();
    assert.equal(await ownInk.isVisible(), true, 'question canvas stays visible under chooser');
    const openBox = await ownInk.boundingBox();
    assert.ok(openBox.width > 0 && openBox.height > 0);
    assert.equal(openBox.width, inkBox.width);
    assert.equal(openBox.height, inkBox.height);
    assert.equal(await list.evaluate(el => getComputedStyle(el).position), 'fixed');
    assert.equal(await list.evaluate(el => getComputedStyle(el).overflowY), 'auto');
    assert.equal(await page.locator('[role="dialog"], .exam-overlay').count(), 0);
    await page.waitForTimeout(600);
    const pausedAt = await page.getByTestId('exam-stopwatch').getAttribute('data-ms');
    await page.waitForTimeout(600);
    assert.equal(await page.getByTestId('exam-stopwatch').getAttribute('data-ms'), pausedAt);
    const rows = list.getByTestId('exam-peer-row');
    assert.equal(await rows.count(),5);
    assert.match(await rows.nth(0).innerText(),/🐱.*수학의 신.*고2.*4분 12초/s);
    assert.match(await rows.nth(1).innerText(),/🦊.*도전자.*고1.*15초/s);
    assert.match(await rows.last().innerText(),/🎓.*선생님.*1분 1초/s);
    assert.ok(!(await list.innerText()).includes('미제출'));
    for (const theme of ['light','dark']) {
      await page.evaluate(async value => { const { applyThemeColor } = await import('/src/utils/theme.ts'); applyThemeColor(value === 'light' ? '#FFFFFF' : undefined); },theme);
      const rect = await list.boundingBox();
      assert.ok(rect.x >= 0 && rect.x + rect.width <= viewport.width && rect.y + rect.height <= viewport.height);
      await list.screenshot({path:`${out}/list-${viewport.width}-${theme}.png`});
      if (viewport.width === 390) await page.screenshot({path:`${out}/question-popover-${theme}.png`});
    }
    const listReadsBefore = await page.evaluate(() => window.__examLog.filter(row=>row.method==='listPeerSolutions').length);
    await page.evaluate(() => {
      const original = window.__examClient.getPeerSolutionByKey;
      let fail = true;
      window.__examClient.getPeerSolutionByKey = async (...args) => {
        if (fail) { fail = false; throw Object.assign(new Error('풀이가 바뀌었어요.'),{code:'EXAM_PEER_CHANGED'}); }
        return original(...args);
      };
    });
    await rows.first().focus();
    await page.keyboard.press('End');
    assert.equal(await rows.last().evaluate(el => el === document.activeElement),true);
    await page.keyboard.press('Home');
    await page.keyboard.press('Enter');
    await page.getByText('풀이가 바뀌었어요. 새 목록에서 다시 골라 주세요.',{exact:true}).waitFor();
    assert.equal(await page.evaluate(() => window.__examLog.filter(row=>row.method==='listPeerSolutions').length),listReadsBefore+1);
    await rows.first().click();
    const peer = page.getByTestId('exam-peer-solution');
    await peer.getByTestId('exam-replay-dock').waitFor();
    assert.equal(await peer.getByTestId('exam-replay-dock').evaluate(el => getComputedStyle(el).position), 'static');
    assert.equal(await list.count(),0);
    assert.match(await peer.getByTestId('exam-peer-label').innerText(),/수학의 신/);
    assert.equal(await peer.getByTestId('exam-audio-sound').count(), 0);
    await checkCanvasPlayback(page, peer);
    await peer.getByRole('slider',{name:'필기 재생 위치'}).press('End');
    await page.waitForFunction(() => document.querySelector('[data-testid="exam-peer-solution"] .exam-ink')?.dataset.strokeCount === '3');
    await peer.getByTestId('exam-peer-toggle').click();
    assert.equal(await peer.locator('.exam-ink').isVisible(), true);
    const peerBox = await peer.locator('.exam-ink').boundingBox();
    assert.ok(peerBox.width > 0 && peerBox.height > 0);
    await peer.getByTestId('exam-peer-label').first().click();
    assert.equal(await list.count(), 0, 'outside tap closes chooser');
    await peer.getByTestId('exam-peer-toggle').click();
    await rows.nth(1).click();
    await peer.getByTestId('exam-replay-dock').waitFor();
    assert.match(await peer.getByTestId('exam-peer-label').innerText(),/도전자/);
    const calls = await page.evaluate(() => window.__examLog.filter(row => row.method==='getPeerSolutionByKey').map(row=>row.args[2]));
    assert.deepEqual(calls,['mock-peer-fingerprint','mock-peer-second']);
    await peer.getByTestId('exam-peer-toggle').click();
    await page.keyboard.press('Escape');
    assert.equal(await list.count(),0); assert.equal(await page.locator('[role="dialog"], .exam-overlay').count(),0);
    await page.keyboard.press('Escape');
    assert.equal(await page.getByTestId('exam-free-peer').evaluate(el=>el===document.activeElement),true);
    assert.equal(await ownInk.getAttribute('data-stroke-count'), '1');
    assert.equal(await ownCanvas.evaluate(el => el === document.querySelector('[data-testid="exam-body"] .exam-ink')), true);
    assert.equal(await page.getByTestId('exam-freecheck').getAttribute('data-correct'),'false');
    await page.getByTestId('exam-free-peer').click();
    await list.waitFor();
    await page.getByRole('button',{name:'다음 문항',exact:true}).click();
    assert.equal(await list.count(),0);
    await page.getByRole('button',{name:'이전 문항',exact:true}).click();
    await page.evaluate(() => {
      const original = window.__examClient.listPeerSolutions;
      window.__examClient.listPeerSolutions = async (...args) => {
        await new Promise(resolve => setTimeout(resolve, 500));
        return original(...args);
      };
    });
    await page.getByTestId('exam-free-peer').click();
    await page.getByTestId('exam-peer-back').waitFor();
    await page.keyboard.press('Escape');
    await page.waitForTimeout(700);
    assert.equal(await list.count(), 0, 'late responses cannot reopen an exited peer session');
    assert.equal(await page.getByTestId('exam-peer-back').count(), 0);
    await ownInk.waitFor();
    await page.getByRole('button',{name:'제출',exact:true}).click();
    await page.getByRole('button',{name:'제출하기',exact:true}).click();
    await page.getByTestId('exam-submit-confirm').click();
    await page.getByTestId('exam-result').waitFor();
    await page.locator('.exam-item-row[data-number="1"]').click();
    await page.getByTestId('exam-peer-toggle').click();
    const resultInk = page.locator('[role="dialog"] .exam-ink').first();
    assert.equal(await resultInk.isVisible(), true);
    const resultBox = await resultInk.boundingBox();
    assert.ok(resultBox.width > 0 && resultBox.height > 0);
    await rows.last().click();
    await peer.getByTestId('exam-replay-dock').waitFor();
    assert.equal(await page.locator('[role="dialog"]').count(), 1);
    assert.match(await peer.getByTestId('exam-peer-label').innerText(),/선생님/);
    assert.equal(await peer.getByTestId('exam-notes-tools').count(),0);
    await checkCanvasPlayback(page, peer);
    assert.deepEqual(errors,[]);
    await page.close();
    console.log(`ok — peer picker free/result selection, switching, keyboard and themes (${viewport.width}px)`);
  }
} finally { await browser.close(); }
